### ISSUE TITLE
Change Text on Tables of Metal Mines to avoid confusions

### ISSUE THREAD

**Issue by mpamiesi** [redigaffi/spaceriders-frontend#238]
Actually the user can think that you only need to use X amount of energy for each upgrade, as it gives sensation of a fix cost, and it’s not like that.

Easy fix is change the text of “Required Energy” to “Energy / Min Cost”.
![1 - req energy](https://user-images.githubusercontent.com/113771379/212490779-963f4c9c-dcd0-471e-867e-71221da103b3.png)
![2 - energy min cost](https://user-images.githubusercontent.com/113771379/212490783-2002ef75-ec5e-45b9-ae21-197b3ae1ca63.png)

**Comment by devjoseruiz** [comment]
Done. Check PR.
